### PR TITLE
ValueGetter code simplification

### PR DESCRIPTION
**Pull request by petrnymsa**
Generated code for ValueGetter can be simplified. 

From 

```
x != null ? x() : this.x
```
to 

```dart
x?.call() ?? this.x
```

### CODE REVIEW

**Comment by ricardoemerson** [comment]
Thanks, I will check

**Comment by ricardoemerson** [comment]
Extension updated, Thanks for contribution, 😉👍

**Comment by petrnymsa** [comment]
@ricardoemerson  This has to be reverted.  Sorry for introducing bug. 

```
x?.call() ?? this.x
```
if ValueGetter returns null, it will fallback to this.x, which is not what we want.

**Comment by petrnymsa** [comment]
@ricardoemerson  Can you look at this, please? It is kinda blocker. Thanks in advance.

**Comment by petrnymsa** [comment]
Opened new PR https://github.com/ricardoemerson/dart-data-class-tools/pull/11

**Pull request merged**
