### PR TITLE
Revert bug in copywith

### PR DESCRIPTION
**Pull request by petrnymsa**
Revert bug introduced in #9

### CODE REVIEW

**Comment by husainazkas** [comment]
this needs to be merged @ricardoemerson

**Comment by petrnymsa** [comment]
> this needs to be merged @ricardoemerson

Yeah, sorry about introducing it in the first place... In the meantime, I've uploaded fork with fix 
https://marketplace.visualstudio.com/items?itemName=PetrNymsa.dart-data-class-tools-nymsa

**Comment by Abdelazeem777** [comment]
@ricardoemerson 

Please accept this PR ASAP

**Comment by ricardoemerson** [comment]
Fixed from source code.

**Pull request closed without merging**
